name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build
          ls

      - name: Copy build files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          strip_components: 3
          source: "/home/runner/work/MoreThanBlog_FE/MoreThanBlog_FE/build/"
          target: "morethan/more-than-blogs-landing/build"

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd morethan
            docker-compose up --detach --build
